# docker-compose.yml

version: '3.8'

services:
  web:
    # Build the image from the Dockerfile in the current directory
    build: .
    
    # The command to run when the container starts
    command: python manage.py runserver 0.0.0.0:8000
    
    # Mount the current directory on your host to /app in the container
    # This allows for live code reloading without rebuilding the image
    volumes:
      - .:/app
      
    # Map port 8000 on your host machine to port 8000 in the container
    ports:
      - "8000:8000"
      
    # Read the .env file and pass the variables to the container
    env_file:
      - .env