# Generated by Django 5.2.4 on 2025-08-13 18:23

import problemset.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('test_case_file', models.FileField(blank=True, null=True, upload_to=problemset.models.get_testcase_json_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
